import Head from 'next/head';
import Image from 'next/image';
import Me from '../assets/Nuevo Logo - copia.jpg'
import Header from '../components/header/Header';
import Nav from '../components/nav/Nav';
import About from '../components/about/About';
import {GiHamburgerMenu} from 'react-icons/gi';

import Services from '../components/services/Services';
import Portfolio from '../components/portfolio/Portfolio';
import Testimonials from '../components/testimonials/Testimonials';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';
import espFlag from '../assets/colFlag.png';
import enFlag from '../assets/enFlag.png';
import { useTranslation } from 'react-i18next';


export default function Home() {

  const [t, i18n] = useTranslation("globals");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <header className='headero'>
         <nav className='navor'>
          <div className='loguito'>
            <Image className='logo' src={Me} alt='Logo' />
          </div>
          <input type='checkbox' id='check' />
          <label htmlFor='check' className='bar-btn'>
            <i className='fa-bars'><GiHamburgerMenu /></i>
          </label>
          <ul className='nav-menu'>
            <li className='active'><a href='#'>Inicio</a></li>
            <li><a href='#portfolio'>Portalio</a></li>
            <li><a href='#contact'>Contacto</a></li>
            <li><a target='blank' href='https://susmedicos.sunu.be/login'>Acceso Plataforma</a></li>
            <li><a target='blank' href='https://www.google.com/maps/dir//Calle+29+AA+%2350+-+09,+Medell%C3%ADn,+Antioquia/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x8e4429b50c9873d9:0xccbf7631256b0d4f?sa=X&ved=2ahUKEwiK_srhzpnsAhXSwFkKHbIuAfkQ9RcwC3oECA8QBA'>Ubicación</a></li>
          </ul>




    
                <div className="containerFlag">
                  <button className='btn-bg' onClick={() => i18n.changeLanguage("es")}>
                    <Image className='btn-flag' src={espFlag} alt="Español" />
                  </button>
                  <button className='btn-bg' onClick={() => i18n.changeLanguage("en")}>
                    <Image className='btn-flag'  src={enFlag} alt="ingles" />
                  </button>

              </div>
         </nav>
       </header>
       <Header />
       <Nav />
       <About />
       <Services />
       <Portfolio />
       <Testimonials />
       <Contact />
       <Footer />
    </>
  )
}
