import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/header/Header';
import Nav from '../components/nav/Nav';
import About from '../components/about/About';
import Experience from '../components/experience/Experience';
import Services from '../components/services/Services';
import Portfolio from '../components/portfolio/Portfolio';
import Testimonials from '../components/testimonials/Testimonials';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';
import espFlag from '../assets/espFlag.png';
import enFlag from '../assets/enFlag.png';
import { useTranslation } from 'react-i18next';


export default function Home() {

  const [t, i18n] = useTranslation("globals");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="containerFlag">
      <button className='btn-bg' onClick={() => i18n.changeLanguage("es")}>
          <Image className='btn-flag' src={espFlag} alt="Español" />
        </button>
        <button className='btn-bg' onClick={() => i18n.changeLanguage("en")}>
          <Image className='btn-flag'  src={enFlag} alt="ingles" />
        </button>
      </div>
       <Header />
       <Nav />
       <About />
       <Experience />
       <Services />
       <Portfolio />
       <Testimonials />
       <Contact />
       <Footer />
    </>
  )
}
