import Head from 'next/head';
import Image from 'next/image';
import Me from '../assets/Nuevo Logo - copia.jpg'
import Header from '../components/header/Header';
import Nav from '../components/nav/Nav';
import About from '../components/about/About';
import Experience from '../components/experience/Experience';
import Services from '../components/services/Services';
import Portfolio from '../components/portfolio/Portfolio';
import Testimonials from '../components/testimonials/Testimonials';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';
import espFlag from '../assets/colFlag.png';
import enFlag from '../assets/enFlag.png';
import { useTranslation } from 'react-i18next';


export default function Home() {

  const [t, i18n] = useTranslation("globals");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='navito'>
        <div className='navo'>
        <Image className='logo' src={Me} alt='Logo' />
          <h3>Portalio</h3>
          <h3>Servicios</h3>
          <h3>Blog</h3>
          <h3>Contacto</h3>
          <h4>Acceso Plataforma</h4>
        </div>
        <p className='infon'>Calle 29AA #50-09</p> 
        <div className="containerFlag">
         
        <button className='btn-bg' onClick={() => i18n.changeLanguage("es")}>
            <Image className='btn-flag' src={espFlag} alt="Español" />
          </button>
          <button className='btn-bg' onClick={() => i18n.changeLanguage("en")}>
            <Image className='btn-flag'  src={enFlag} alt="ingles" />
          </button>
        </div>
      </div>
       <Header />
       <Nav />
       <About />
       <Experience />
       <Services />
       <Portfolio />
       <Testimonials />
       <Contact />
       <Footer />
    </>
  )
}
